name: Mobile Type Check (Expo)

on:
  pull_request:
    branches: ["main"]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Path2IvyMobile
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Path2IvyMobile/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: TypeScript check
        run: npx tsc -p tsconfig.json --noEmit


